"""add hashed_password to users

Revision ID: 9dbd344a3254
Revises: 9a9d169a81e6
Create Date: 2026-07-22 11:11:48.897004

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dbd344a3254"
down_revision: Union[str, Sequence[str], None] = "9a9d169a81e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "users",
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.execute("""
        UPDATE users
        SET hashed_password = 'TEMP_PASSWORD'
        WHERE hashed_password IS NULL
        """)

    op.alter_column(
        "users",
        "hashed_password",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
